server:
  port: 8082

spring:
  application:
    name: user-service
  devtools:
    restart:
      enabled: true

  cloud:
    consul:
      host: localhost
      port: 8500
    config:
      discovery:
        enabled: false
        service-id: config-server
