server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    consul:
      host: localhost
      port: 8500
    config:
      server:
        git:
          uri: https://gitlab.p168v.com
          clone-on-start: false
          search-paths: {application}
